### ISSUE TITLE
web\extensions\Bmad

### ISSUE THREAD

**Issue by alexbofa** [bmad4ever/ComfyUI-Bmad-Custom-Nodes#5]
Hello. What can it mean? How to solve this problem?
```
From Bmad Custom Nodes
 Loaded 66 nodes:
  + api nodes (14)
  + simple utility nodes (21)
  + CV nodes (28)
  + color clip ade20k node (1)
  + extension dependent nodes (2)
 Problems:
  ! "web\extensions\Bmad" folder is missing, some nodes won't work as intended.
```

![Screen-2271](https://github.com/bmad4ever/ComfyUI-Bmad-Custom-Nodes/assets/58225118/9744d61f-fe76-4540-8b2a-3a5081139e82)

**Comment by bmad4ever** [comment]
It appears that after the repo structure was updated, I forgot to copy the javascript files to the web extensions folder in init.py.
It should be easy to fix, and I will solve it as soon as possible (if not today, tomorrow).

If you want to fix it right now to try the nodes, you only have to create a folder named Bmad in the web/extensions directory and move all the javascript files there.

**Comment by alexbofa** [comment]
Thank you, I got you!

**Comment by bmad4ever** [comment]
just updated init.py, it should be fixed now.

**Comment by alexbofa** [comment]
Thx!
